import PhotoA200 from 'images/versions/a200.png';

const MockVersions = [
  {
    name: 'A 200',
    photo: PhotoA200,
    informations: [
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Potência Máxima EEC - Cv', value: '240' },
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'em rev/min', value: '2,000-4000' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
    ],
    tags: [
      'Ar Condicionado',
      'Air Bag',
      'Desembaçador Traseiro',
      'Ar Quente',
      'Freios ABS',
      'Teto Solar',
      'AirBag',
      'Teto Solar',
      'Ar Quente',
      'Freios ABS',
      'Teto Solar',
      'Air Bag',
      'Ar Condicionado',
      'Desembaçador Traseiro',
    ],
  },
  {
    name: 'A 250 Turbo Sport',
    photo: PhotoA200,
    informations: [
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Potência Máxima EEC - Cv', value: '240' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'em rev/min', value: '2,000-4000' },
    ],
    tags: [
      'Freios ABS',
      'Teto Solar',
      'Air Bag',
      'Ar Condicionado',
      'Desembaçador Traseiro',
      'Ar Condicionado',
      'Air Bag',
      'Desembaçador Traseiro',
      'Ar Quente',
      'AirBag',
      'Teto Solar',
      'Ar Quente',
    ],
  },
  {
    name: 'A 45 AMG 4Matic',
    photo: PhotoA200,
    informations: [
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'em rev/min', value: '2,000-4000' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Potência Máxima EEC - Cv', value: '240' },
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Cilindros/vávulas por cilindros', value: '4/4' },
      { title: 'Em rev/min', value: '5,500' },
      { title: 'Cilindrada(cc)', value: '1,999' },
      { title: 'Torque máximo EEC - Nm(libra-pé)', value: '340' },
      { title: 'Diâmetro/curso(mm)', value: '87.5/8.31' },
    ],
    tags: [
      'Ar Quente',
      'Desembaçador Traseiro',
      'Ar Condicionado',
      'Air Bag',
      'Freios ABS',
      'Ar Quente',
      'Teto Solar',
      'AirBag',
      'Teto Solar',
      'Freios ABS',
      'Ar Condicionado',
    ],
  },
];

export default MockVersions;
